[package]
name = "kata05_rpg_combat"
version = "0.1.0"
authors = ["Ruslan Fadeev <github@kinrany.dev>"]
edition = "2021"

[dependencies]
thiserror = "1.0.49"
uuid = { version = "1.4.1", features = ["v4"] }
